### ISSUE TITLE
Shouldn't be so confident on queries with < 2 words

### ISSUE THREAD

**Issue by MatthewScholefield** [MatthewScholefield/padatious-native#10]
Sometimes intents are 0.8 or more confident with the query `' '`. Even a single period will trigger some intents. This should be inhibited.

**Comment by kfezer** [comment]
also just 'a' get's a pretty solid confidence:
```
Intent: goodbye.intent
Confidence: 0.64
```
There are cases where I would want to see 1 small word actually succeed, like 'NPR' for example. 

It could be weighted based on size maybe of utterance, maybe

**Comment by MatthewScholefield** [comment]
It should now be weighting words based on the length. See how it is now.
